blog/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    CategoryView,
    LikeView,
    AddCommentView,
    LatestPostView
)
from . import views


urlpatterns = [
    path('', views.home, name='blog-home'),
    path('latest_posts/', LatestPostView.as_view(), name='latest-post'),
    path('photo_gallery/', views.photo_gallery, name='photo-gallery'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='blog-about'),
    path('category/<str:cats>/', CategoryView, name='category'),
    path('like/<int:pk>', LikeView, name='like_post'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('enquiries/', views.enquiries, name='enquiries'),
    path('latest_videos/', views.latest_videos, name='video'),
    path('video/', views.video, name='video_one'),
    path('video_two/', views.video_two, name='video_two'),
    path('video_three/', views.video_three, name='video_three'),
    path('video_four/', views.video_four, name='video_four'),
    path('post/<int:pk>/comment', AddCommentView.as_view(), name='add_comment'),
    path('search', views.search, name="search"),
]

cloud/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve

from . import views


app_name = 'files_home'
urlpatterns = [
    path('', views.files_home_view, name="files_home"),
    path('download/', views.download_view, name="download_file"),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.views.static import serve

admin.site.site_header = "Diamond Nepal"
admin.site.site_title = "Diamond Nepal"
admin.site.index_title = "Diamond Nepal Dashboard"

urlpatterns = [
    path('s/', include('url.urls')),
    path('cloud/', include('cloud.urls', namespace='files_home')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('password_change/', 
        auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('', include('blog.urls'))
]

handler404 = "blog.views.view_404"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

url/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>/', views.redirector_view),
    path('', views.home_view),
    path('api/shorten-url/', views.url_shortener_api, name='url_shortener_api'),
    path('api/shorten-url', views.url_shortener_api, name='url_shortener_api_safe'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
#from ckeditor.fields import RichTextField

class Category(models.Model):
	name = models.CharField(max_length=80)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('blog-home')

class Post(models.Model):
    title = models.CharField(max_length=100)
    #content = RichTextField(blank=True, null=True)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    likes = models.ManyToManyField(User, related_name='blog_posts')
    post_image = models.ImageField(null=True, blank=True, upload_to="user_posts_images/")

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title + " | " + str(self.author) 

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})
 
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    your_name = models.CharField(max_length=30)
    comment = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s | %s" % (self.post.title, self.name)

cloud/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save


class File(models.Model):
	upload = models.FileField(upload_to='cloud_files')

	location = models.CharField(max_length=500, null=True)
	file_type = models.CharField(max_length=100, null=True)
	size = models.IntegerField(null=True)
	upload_datetime = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.upload.name.replace('cloud_files/', '')

	def readable_name(self):
  		return self.upload.name.replace('cloud_files/', '')

	def size_mb(self):
		mb = round((int(self.upload.size) / 1024)/1024, 2) 
		return mb


def pre_save_file_info(sender, instance, *args,**kwargs):
	instance.location = instance.upload.url
	instance.size = instance.upload.size

pre_save.connect(pre_save_file_info, sender=File)

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('your_name', 'comment')

		widgets = {
			'your_name': forms.TextInput(attrs={'class':'form-control'}),
			'comment': forms.Textarea(attrs={'class':'form-control'}),
		}

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post, Comment, Category
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from .forms import CommentForm
from django.urls import reverse_lazy
import requests
import json


verified_users = [1,2,3,4,5,6,7,8,9,10]

@login_required
def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    
    return HttpResponseRedirect(reverse('post-detail', args=[str(pk)]))


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5
    extra_context = {'verified_users':verified_users}
    
    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')

class PostDetailView(DetailView):
    model = Post
    extra_context = {'verified_users':verified_users}

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'category', 'post_image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ('title', 'content', 'category', 'post_image')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def CategoryView(request, cats):
    category_posts = Post.objects.filter(category=cats).order_by('-date_posted')
    return render(request, 'blog/categories.html', {'verified_users':verified_users,'cats':cats, 'category_posts':category_posts})

def about(request):
    who = User.objects.filter(username='About-DiamondNepal').first()
    context = { 
        'posts': who.post_set.all()
    }
    return render(request, 'blog/about.html', context)


def home(request):
    new_posts = Post.objects.all().order_by('-date_posted').first()
    sahitya_posts = Post.objects.filter(category=4).order_by('-date_posted').first()
    nepalinews_posts = Post.objects.filter(category=2).order_by('-date_posted').first()
    parbshinews_posts = Post.objects.filter(category=3).order_by('-date_posted').first()
    entertainment_posts = Post.objects.filter(category=1).order_by('-date_posted').first()
    return render(request, 'blog/home.html', {'verified_users':verified_users, 'latest':new_posts,'parbshi':parbshinews_posts, 'sahitya':sahitya_posts, 'nepalinews':nepalinews_posts, 'entertainment':entertainment_posts})

class LatestPostView(ListView):
    model = Post
    template_name = 'blog/latest_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 7

def photo_gallery(request):
    return render(request, 'blog/photo_gallery.html') 

def privacy_policy(request):
    return render(request, 'blog/privacy_policy.html')

def enquiries(request):
    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        message_username = request.POST['message-username']
        # reCAPTCHA

        clientkey = request.POST['g-recaptcha-response']
        secretkey = '6LclBbYZAAAAALFIsTLeuw-egg_zdxPjcA0YfZBW'
        captcha = {
            'secret':secretkey,
            'response':clientkey
        }

        r = requests.post('https://www.google.com/recaptcha/api/siteverify', data=captcha)
        response = json.loads(r.text)
        verify = response['success']

        if verify:
            # Sending Email
            send_mail(
                'Enquiry From : ' + str(message_name),
                'This is an Enquiry from : ' + str(message_name) + "\nUsername: "+ str(message_username) + ',\nYou are supposed to respond to this Enquiry at : ' + str(message_email) + '\nThe Enquiry is :\n' + str(message),
                'noreply@diamondnepal.com',
                ['contact@diamondnepal.com']
                )

            return render(request, 'blog/enquiry_form.html', {'message_name':message_name, 'message_email': message_email})
        else:
            return render(request, 'blog/enquiry_form.html', {'message_name':message_name, 'recaptcha_error':"Please tick the box where it says, 'I am not a robot!'"})

    else:    
        return render(request, 'blog/enquiry_form.html')

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    ordering = ['-date_added']
    template_name = "blog/add_comment.html"
    success_url = reverse_lazy('blog-home')

    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)


def view_404(request, exception):
    return render(request, 'blog/404.html')

def latest_videos(request):
    return render(request, 'blog/latest_videos.html')

def video(request):
    return render(request, 'blog/video.html')

def video_two(request):
    return render(request, 'blog/video2.html')

def video_three(request):
    return render(request, 'blog/video3.html')

def video_four(request):
    return render(request, 'blog/video4.html')

def search(request):
    query = request.GET['query']

    if len(query) > 80:
        posts = Post.objects.none()
    else:
        PostTitle = Post.objects.filter(title__icontains=query)
        PostContent = Post.objects.filter(content__icontains=query)
        posts = PostTitle.union(PostContent)
        PostUser = User.objects.filter(username__icontains=query)
        try:
            PostUser = PostUser[0].post_set.all()
            posts = posts.union(PostUser)
        except:
            pass

    if posts.count() == 0:
        print(query.lower())
        if "entert" in query.lower():
            query = 1
            category_posts = Post.objects.filter(category=query)
            return render(request, 'blog/categories.html', {'verified_users':verified_users, 'category_posts':category_posts})

        elif query.lower() == "sahitya" or "nepali" in query.lower():
            query = 4
            category_posts = Post.objects.filter(category=query)
            return render(request, 'blog/categories.html', {'verified_users':verified_users, 'category_posts':category_posts})

        elif query.lower() == "video" or query.lower() == "videos":
            return render(request, 'blog/latest_videos.html')

        elif "news" in query.lower() or "news" in query.lower():
            import random
            x = random.randint(1,2)
            if x == 1:
                query = 2
                category_posts = Post.objects.filter(category=query)
                return render(request, 'blog/categories.html', {'verified_users':verified_users, 'category_posts':category_posts})
            else:
                query = 3
                category_posts = Post.objects.filter(category=query)
                return render(request, 'blog/categories.html', {'verified_users':verified_users, 'category_posts':category_posts})               
        else:
            pass

    context = {'posts':posts, 'query':query, 'verified_users':verified_users}

    return render(request, 'blog/search.html', context)

cloud/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.conf import settings
from .models import File
import os

file_content_types = [
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'application/pdf',
	'image/png',
	'text/plain',
	'audio/mp3'
]

# Create your views here.
def files_home_view(request):
	context = {}

	if request.method == 'POST':
		uploaded_file = request.FILES['my_file']
		if uploaded_file.content_type not in file_content_types:
			print("INVALID CONTENT TYPE")

		else:
			new_file = File(upload=uploaded_file, file_type=uploaded_file.content_type)
			new_file.save()
			print(uploaded_file.content_type)

	qs = File.objects.all().order_by('-upload_datetime')
	context['files'] = qs

	context["file_types"] = file_content_types
	file_type_counts = []
	for file_type in file_content_types:
		count = File.objects.filter(file_type=file_type).count()
		file_type_counts.append(count)
	context["file_type_counts"] = file_type_counts

	# Server Status
	import psutil
	hdd = psutil.disk_usage('/')
	mem = psutil.virtual_memory()
	context["DISK1"] = "Total : " + str(int(round(hdd.total / (2**30),0))) + " GB\n" 
	context["DISK2"] = "Free : " + str(int(round(hdd.free / (2**30),0))) + " GB"
	context["CPU"] = psutil.cpu_percent()
	context["RAM"] = mem.percent

	return render(request, "cloud/home.html", context)


def download_view(request):
	if request.method == 'POST':
		path = request.POST.get('path')
		print(path)
		file_path = os.path.join(settings.MEDIA_ROOT, path)
		if os.path.exists(file_path):
			with open(file_path, 'rb') as fh:
				response = HttpResponse(fh.read(), content_type="application/force-download")
				response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
				return response
	raise Http404

blog/templates/cloud/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
  	<meta charset="utf-8">
    	<meta name="description" content="Cloud server which gives you access to upload and download from anywhere.">
   	<meta name="author" content="Lissan Koirala">
   	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
	<link rel='shortcut icon' type='image/png' href="https://diamondnepal.com/media/cloud.png" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<title>Cloud Server</title>

  </head>
  <body>
		<main role="main" class="container">
			<br/>
			<h1>Cloud Server</h1><h4>Welcome, {% if user.username %}{{ user.username }}{% else %}Guest{% endif %}</h4><br>
			<div class="row">
				<div class="col-md-4">
					{% if user.is_superuser %}
					<table class="table">
						<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Disk Usage</th>
						</tr>
						</thead>
						<tbody>
						<tr>
							<th scope="row">-</th>
							<td>{{ DISK1 }}</td>
						</tr>
						<tr>
							<th scope="row">-</th>
							<td>{{ DISK2 }}</td>
						</tr>
						</tbody>
					</table>
				</div>

				<div class="col-md-4">
					<table class="table">
						<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Server Info</th>
						</tr>
						</thead>
						<tbody>
						<tr>
							<th scope="row">-</th>
							<td>CPU : {{ CPU }}%</td>
						</tr>
						<tr>
							<th scope="row">-</th>
							<td>RAM : {{ RAM }}%</td>
						</tr>
						</tbody>
					</table>
				{% endif %}
				</div>
			</div>
			<br/>
			<hr>
			{% if user.is_superuser %}
				<form method="post" enctype="multipart/form-data">{% csrf_token %}
					<input type="file" name="my_file">
					<button class="btn btn-success" type="submit">Upload</button>
				</form>
				<hr>
			{% endif %}
			<h2>Uploaded Files</h2><br>
			<table class="table">
			<thead>
				<tr>
				<th scope="col">#</th>
				<th scope="col">File name</th>
				<th scope="col">Size</th>
				<th scope="col">File Type</th>
				<th scope="col">Upload Date</th>
				<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				{% for file in files %}
					{% url 'files_home:download_file' as download_file_url%}
	
					<tr>
					<th scope="row">{{ forloop.counter }}</th>
					<td>{{ file.readable_name }}</td>
					<td>{{ file.size_mb }} MB</td>
					<td>{{ file.file_type }}</td>
					<td>{{ file.upload_datetime|date:"F d, Y" }}</td>
					<td>
						<form action="{{ download_file_url }}" method="post">
						{% csrf_token %}
						{{ form }}
						<input type="hidden" name="path" value="{{ file.upload.name }}">
						<input type="submit" class="btn btn-primary label-success" value="Download" />
						</form>
					</td>
					</tr>
	
				{% endfor %}
			</tbody>
			</table>
			<hr>
			<br><br>
		</main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>